[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = [{{ cookiecutter.supported_python_versions }}]

[tool.isort]
profile = "black"
